// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_2_TaskApp.Models;

namespace Project_2_TaskApp.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Project_2_TaskApp.Models.TaskData", b =>
                {
                    b.Property<int>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("quadrant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("taskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            taskId = 1,
                            category = "School",
                            completed = false,
                            dueDate = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            quadrant = "Urgent, Important",
                            taskName = "Homework"
                        },
                        new
                        {
                            taskId = 2,
                            category = "Work",
                            completed = true,
                            dueDate = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            quadrant = "Not Urgent, Important",
                            taskName = "Job Stuff"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
